# Generated by Django 3.1.1 on 2021-03-08 15:57

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Povrce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name of vegetable')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Vegetables Address')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('vrsta', models.CharField(choices=[('nedefinirano', 'Nedefinirano'), ('plodasto', 'Plodasto'), ('cvjetasto', 'Cvjetasto'), ('lisnato', 'Lisnato'), ('stabljicasto', 'Stabljicasto'), ('lukovicasto', 'Lukovicasto'), ('korjenasto', 'Korjenasto'), ('mahunasto', 'Mahunasto'), ('gomoljasto', 'Gomoljasto')], default='nedefinirano', max_length=30, verbose_name='Vegetable species')),
                ('country_of_origin', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country of Origin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
